### ISSUE TITLE
Oops! Service 'authorizedkeys': 'value' field is required

### ISSUE THREAD

**Issue by tbrooke** [tutumcloud/authorizedkeys#1]
I am a newbie I get the following message when trying to create the stack

Oops!
Service 'authorizedkeys': 'value' field is required

Only change I made was to paste in my rsa key

**Comment by tifayuki** [comment]
It looks like `- AUTHORIZED_KEYS=xxxxx`
did you remove the `=` in the stack file?

**Comment by tbrooke** [comment]
authorizedkeys:
  image: tutum/authorizedkeys
  deployment_strategy: every_node
  autodestroy: always
  environment:
    - AUTHORIZED_KEYS=ssh-rsa asa  << I deleted the rest of the key >> 
    - /root:/user:rw

**Comment by tifayuki** [comment]
you missed `volumes:`, the line before`- /root:/user:rw`

**Comment by tbrooke** [comment]
Got it -- When  I cut the existing key to replace it with mine I was getting the next line and deleting the volume:  works fine
